wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1676224934.274107
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.10.8
      5: 0.13.9
      8:
      - 5
batch_size:
  desc: null
  value: 128
device:
  desc: null
  value: cuda
epochs:
  desc: null
  value: 1000
learning_rate:
  desc: null
  value: 0.005
method_scaling:
  desc: null
  value: std
output_length:
  desc: null
  value: 1
withlogtrans:
  desc: null
  value: false
